global:
    scrape_interval:     15s
    evaluation_interval: 15s 
scrape_configs:
- job_name: 'kafka'
  static_configs:
   # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
  - targets: ['kafka-exporter:5556']