"""add esb request

Revision ID: d7ff1e5d12ac
Revises:
Create Date: 2024-12-21 22:25:00.333460

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d7ff1e5d12ac"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "esb_requests",
        sa.Column("id", sa.UUID(), nullable=False, comment="ID"),
        sa.Column(
            "type",
            sa.Enum(
                "SEND_EMAIL_MSG",
                "SEND_TG_MSG",
                name="esbrequesttype",
                native_enum=False,
            ),
            nullable=False,
            comment="Тип сообщения",
        ),
        sa.Column(
            "state",
            sa.Enum(
                "SENDING",
                "SENDING_ERROR",
                "SENT",
                "RESPONSE_SUCCESS",
                "RESPONSE_ERROR",
                "CANCELLED",
                name="esbrequeststate",
                native_enum=False,
            ),
            nullable=False,
            comment="Состояние сообщения",
        ),
        sa.Column(
            "body",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=False,
            comment="Тело сообщения",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
            comment="Дата последнего обновления",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("esb_requests")
    # ### end Alembic commands ###
