- id: ruff
  name: ruff
  description: "Ruff linting"
  entry: ruff check
  language: python
  types_or: [python, pyi]
  args: [ --fix --select I]
  require_serial: true
  additional_dependencies: []
  minimum_pre_commit_version: "2.9.2"

- id: ruff-format
  name: ruff-format
  description: "Ruff formatting"
  entry: ruff format
  language: python
  types_or: [python, pyi]
  args: []
  require_serial: true
  additional_dependencies: []
  minimum_pre_commit_version: "2.9.2"